language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

  before_script:
	- wget http://mirrors.linuxeye.com/jdk/jdk-6u45-linux-x64.bin
	- chmod a+x jdk-6u45-linux-x64.bin	
	- ./jdk-6u45-linux-x64.bin
	- sudo mkdir /usr/lib/jvm
	- sudo mv jdk1.6.0_45 /usr/lib/jvm/  
	- sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk1.6.0_45/bin/javac 1  
	- sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk1.6.0_45/bin/java 1  
	- sudo update-alternatives --install /usr/bin/javaws javaws /usr/lib/jvm/jdk1.6.0_45/bin/javaws 1 
	- sudo update-alternatives --config javac  
	- sudo update-alternatives --config java  
	- sudo update-alternatives --config javaws
	- ls -la /etc/alternatives/java*

  script: ./build.sh

