language: c

#######################################################################################


os:
  - linux


#######################################################################################


before_install:

  - sudo apt-get update -qq
  
  # downloading the latest version of the linaro toolchain. 
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 ~/arm-eabi-4.8/

#######################################################################################


script:  
  - ./travis.sh 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 069f1d922a68e07a800abab24fac58e4d0d84aaa # Set in travis-ci.org dashboard
  on:
    branch: master
