language: android
android:
   components:
    - ant
    - tools
    - platform-tools

   before_install:
    - sudo apt-get update
    - sudo apt-get install mingw-w64 git gnupg flex bison gperf build-essential zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib mingw32 tofrodos python-markdown libxml2-utils xsltproc zlib1g-dev:i386 git-core lzop ccache gnupg flex bison gperf build-essential zip curl zlib1g-dev zlib1g-dev:i386 libc6-dev lib32ncurses5 lib32z1 lib32bz2-1.0 lib32ncurses5-dev x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 lib32z-dev libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib mingw32 tofrodos python-markdown libxml2-utils xsltproc readline-common libreadline6-dev libreadline6 lib32readline-gplv2-dev libncurses5-dev lib32readline5 lib32readline6 libreadline-dev libreadline6-dev:i386 libreadline6:i386 bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev lib32bz2-dev libsdl1.2-dev libesd0-dev squashfs-tools pngcrush schedtool libwxgtk2.8-dev python gcc g++ cpp gcc-4.8 g++-4.8

   before_script:
    - wget http://mirrors.linuxeye.com/jdk/jdk-6u45-linux-x64.bin
    - chmod a+x jdk-6u45-linux-x64.bin	
    - ./jdk-6u45-linux-x64.bin
    - sudo mkdir /usr/lib/jvm
    - sudo mv jdk1.6.0_45 /usr/lib/jvm/  
    - sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk1.6.0_45/bin/javac 1  
    - sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk1.6.0_45/bin/java 1  
    - sudo update-alternatives --install /usr/bin/javaws javaws /usr/lib/jvm/jdk1.6.0_45/bin/javaws 1 
    - sudo update-alternatives --config javac  
    - sudo update-alternatives --config java  
    - sudo update-alternatives --config javaws
    - ls -la /etc/alternatives/java*

   script: ./build.sh

